# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Noah DeMarco
email: noah.demarco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Noah DeMarco's personal site - still under construction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://noahd.com" # the base hostname & protocol for your site
twitter_username: noah_bits
github_username:  demarna1

# Build settings
markdown: kramdown
